public class TriggerHandler {
    public static void triggerMethod1(){
        System.debug('This is handler class. Before Update');
    }
    public static void triggerMethod2(){
        System.debug('This is handler class. Before Insert');
    }
}
/*HANDLER
public class TriggerHandler {
    public static void triggerMethod1(){
        System.debug(‘This is handler class. Before Update’);
    }
    public static void triggerMethod2(){
        System.debug(‘This is handler class. Before Insert’);
    }
}*/